
apiVersion: 1
kind: CronJob
metadata:
  name: commitlint-bot
spec:
  schedule: "0 17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: config-vol
              configMap:
                name: rr-ftp-config
          cotainers:
          - name: rr-ftp
            image: quay.io/getswift/rr-ftp:v1.1.0
            volumeMounts:
            - name: config-vol
              mountPath: /app/config
            command:
              - /app/rr-ftp
          restartPolicy: OnFailure