
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commitlint-bot
spec:
  replicas: 1
  selector:
      matchLabels:
          app: commitlint-bot
  template:
    metadata:
      labels: 
        app: commitlint-bot
        
    spec:
      volumes:
        - name: config-vol
          configMap:
            name: commitlint-bot-config
      imagePullSecrets: [
          {
            "name": "dockerhub"
          },
          {
            "name": "quay"
          }
        ]
      containers:
      - name: commitlint-bot
        image: quay.io/getswift/commitlint-bot
        volumeMounts:
        - name: config-vol
          mountPath: /
        command:
          - npm start